#title: Minimal theme
#logo: /assets/img/logo.png
#description: Minimal is a theme for GitHub Pages.
#show_downloads: true
#google_analytics:
#theme: jekyll-theme-minimal

title: Mattias G
description: Portfolio – Cybersecurity, Design, and Code
remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

show_downloads: false
